#include "utils.hpp"

namespace nucc {
    namespace ASBR {

std::unordered_map<std::string, std::string> character_id_reflist = {
    {"Baoh",                            "0bao01"},
    {"Ikuro Hashizawa",                 "0bao01"},
    {"Ikuro",                           "0bao01"},
    {"Hashizawa",                       "0bao01"},
    // Part 1: Phantom Blood
    {"Dio Brando",                      "1dio01"},
    {"Dio",                             "1dio01"},
    {"Jonathan Joestar",                "1jnt01"},
    {"Jonathan",                        "1jnt01"},
    {"Robert E. O. Speedwagon",         "1sdw01"},
    {"Speedwagon",                      "1sdw01"},
    {"REO Speedwagon",                  "1sdw01"},
    {"R.E.O. Speedwagon",               "1sdw01"},
    {"Will A. Zeppeli",                 "1zpl01"},
    {"Will A Zeppeli",                  "1zpl01"},
    {"Will Anthonio Zeppeli",           "1zpl01"},
    {"William Anthonio Zeppeli",        "1zpl01"},
    {"William A. Zeppeli",              "1zpl01"},
    {"William A Zeppeli",               "1zpl01"},
    {"Baron Zeppeli",                   "1zpl01"},
    {"Zeppeli",                         "1zpl01"},
    // Part 2: Battle Tendency
    {"Caesar Anthonio Zeppeli",         "2csr01"},
    {"Caesar Zeppeli",                  "2csr01"},
    {"Caesar",                          "2csr01"},
    {"Caesar A Zeppeli",                "2csr01"},
    {"Caesar A. Zeppeli",               "2csr01"},
    {"Esidisi",                         "2esd01"},
    {"AC/DC",                           "2esd01"},
    {"Joseph Joestar",                  "2jsp01"},
    {"Joseph",                          "2jsp01"},
    {"Lisa Lisa (Elizabeth)",           "2lsa01"},
    {"Lisa Lisa",                       "2lsa01"},
    {"Elizabeth Joestar",               "2lsa01"},
    {"Elizabeth",                       "2lsa01"},
    {"Kars",                            "2krs01"},
    {"Rudol von Stroheim",              "2shm01"},
    {"Stroheim",                        "2shm01"},
    {"Wamuu",                           "2wmu01"},
    {"Wham",                            "2wmu01"},
    {"Wham!",                           "2wmu01"},
    // Part 3: Stardust Crusaders
    {"Muhammad Avdol",                  "3abd01"},
    {"Mohammed Avdol",                  "3abd01"},
    {"Muhammad Abdul",                  "3abd01"},
    {"Mohammed Avdol",                  "3abd01"},
    {"Avdol",                           "3abd01"},
    {"Abdul",                           "3abd01"},
    {"DIO",                             "3dio01"},
    {"Hol Horse",                       "3hhs01"},
    {"Iggy",                            "3igy01"},
    {"Old Joseph Joestar",              "3jsp01"},
    {"Old Joseph",                      "3jsp01"},
    {"Oldseph",                         "3jsp01"},
    {"Jotaro Kujo",                     "3jtr01"},
    {"Jotaro",                          "3jtr01"},
    {"Noriaki Kakyoin",                 "3kki01"},
    {"Kakyoin",                         "3kki01"},
    {"Noriaki",                         "3kki01"},
    {"Mariah",                          "3mra01"},
    {"Jean Pierre Polnareff",           "3pln01"},
    {"Polnareff",                       "3pln01"},
    {"Jean Pierre",                     "3pln01"},
    {"Pet Shop",                        "3psp01"},
    {"Vanilla Ice",                     "3vni01"},
    // Part 4: Diamond is Unbreakable
    {"Yuya Fungami",                    "4fgm01"},
    {"Yuya",                            "4fgm01"},
    {"Fungami",                         "4fgm01"},
    {"Josuke Higashikata",              "4jsk01"},
    {"Josuke",                          "4jsk01"},
    {"Jotaro Kujo (Part 4)",            "4jtr01"},
    {"Jotaro Kujo 4",                   "4jtr01"},
    {"Jotaro (Part 4)",                 "4jtr01"},
    {"Jotaro 4",                        "4jtr01"},
    {"Keicho Nijimura",                 "4kch01"},
    {"Keicho",                          "4kch01"},
    {"Yoshikage Kira",                  "4kir01"},
    {"Kira",                            "4kir01"},
    {"Yoshikage",                       "4kir01"},
    {"Koichi Hirose",                   "4koi01"},
    {"Koichi",                          "4koi01"},
    {"Kosaku Kawajiri",                 "4kwk01"},
    {"Kosaku",                          "4kwk01"},
    {"Okuyasu Nijimura",                "4oky01"},
    {"Okuyasu",                         "4oky01"},
    {"Akira Otoishi",                   "4oti01"},
    {"Akira",                           "4oti01"},
    {"Otoishi",                         "4oti01"},
    {"Rohan Kishibe",                   "4rhn01"},
    {"Rohan",                           "4rhn01"},
    {"Kishibe",                         "4rhn01"},
    {"Shigekiyo Yangu",                 "4sgc01"},
    {"Shigekiyo",                       "4sgc01"},
    {"Shigechi",                        "4sgc01"},
    {"Yukako Yamagishi",                "4ykk01"},
    {"Yukako",                          "4ykk01"},
    {"Yamagishi",                       "4ykk01"},
    // Parte 5: Vento Aureo
    {"Leone Abbacchio",                 "5abc01"},
    {"Abbacchio",                       "5abc01"},
    {"Leone",                           "5abc01"},
    {"Bruno Bucciarati",                "5bct01"},
    {"Bucciarati",                      "5bct01"},
    {"Bruno",                           "5bct01"},
    {"Diavolo",                         "5dvl01"},
    {"Pannacotta Fugo",                 "5fgo01"},
    {"Fugo",                            "5fgo01"},
    {"Pannacotta",                      "5fgo01"},
    {"Ghiaccio",                        "5gac01"},
    {"Giorno Giovanna",                 "5grn01"},
    {"Giorno",                          "5grn01"},
    {"Giovanna",                        "5grn01"},
    {"Haruno Shiobana",                 "5grn01"},
    {"Haruno",                          "5grn01"},
    {"Shiobana",                        "5grn01"},
    {"Guido Mista",                     "5mst01"},
    {"Mista",                           "5mst01"},
    {"Guido",                           "5mst01"},
    {"Narancia Ghirga",                 "5nrc01"},
    {"Narancia",                        "5nrc01"},
    {"Ghirga",                          "5nrc01"},
    {"Prosciutto & Pesci",              "5prs01"},
    {"Prosciutto",                      "5prs01"},
    {"Pesci",                           "5prs01"},
    {"Risotto Nero",                    "5ris01"},
    {"Risotto",                         "5ris01"},
    {"Trish Una",                       "5trs01"},
    {"Trish",                           "5trs01"},
    // Part 6: Stone Ocean
    {"Narciso Anasui",                  "6ans01"},
    {"Anasui",                          "6ans01"},
    {"Narciso",                         "6ans01"},
    {"Ermes Costello",                  "6elm01"},
    {"Ermes",                           "6elm01"},
    {"Foo Fighters",                    "6fit01"},
    {"F.F.",                            "6fit01"},
    {"FF",                              "6fit01"},
    {"Jolyne Cujoh",                    "6jln01"},
    {"Jolyne",                          "6jln01"},
    {"Enrico Pucci (Final)",            "6pci01"},
    {"Enrico Pucci Final",              "6pci01"},
    {"Pucci (Final)",                   "6pci01"},
    {"Pucci Final",                     "6pci01"},
    {"Enrico Pucci",                    "6pci02"},
    {"Enrico Pucci (Whitesnake)",       "6pci02"},
    {"Enrico Pucci Whitesnake",         "6pci02"},
    {"Pucci",                           "6pci02"},
    {"Pucci (Whitesnake)",              "6pci02"},
    {"Pucci Whitesnake",                "6pci02"},
    {"Weather Report",                  "6wet01"},
    {"Weather",                         "6wet01"},
    {"Wes Bluemarine",                  "6wet01"},
    {"Wes",                             "6wet01"},
    // Part 7: Steel Ball Run
    {"Diego Brando",                    "7dio01"},
    {"Diego",                           "7dio01"},
    {"Scary Monsters Diego Brando",     "7dio01"},
    {"Scary Monsters Diego",            "7dio01"},
    {"Parallel World Diego Brando",     "7dio02"},
    {"Parallel World Diego",            "7dio02"},
    {"Parallel Diego Brando",           "7dio02"},
    {"Parallel Diego",                  "7dio02"},
    {"Diego THE WORLD",                 "7dio02"},
    {"Diego (THE WORLD)",               "7dio02"},
    {"Diego Brando THE WORLD",          "7dio02"},
    {"Diego Brando (THE WORLD)",        "7dio02"},
    {"Gyro Zeppeli",                    "7jir01"},
    {"Gyro",                            "7jir01"},
    {"Johnny Joestar",                  "7jny01"},
    {"Johnny",                          "7jny01"},
    {"Funny Valentine",                 "7vtn01"},
    {"Valentine",                       "7vtn01"},
    {"Funny",                           "7vtn01"},
    // Part 8: JoJolion
    {"Josuke Higashikata (JoJolion)",   "8jsk01"},
    {"Josuke Higashikata 8",            "8jsk01"},
    {"Josuke (JoJolion)",               "8jsk01"},
    {"Josuke 8",                        "8jsk01"},
    {"Gappy",                           "8jsk01"},
    {"Hat Josuke",                      "8jsk01"},
    {"Hatsuke",                         "8jsk01"},
    {"Toru",                            "8wou01"},
    {"Tooru",                           "8wou01"},
    {"Wonder of U",                     "8wou01"}
};

std::string get_character_id_ref(std::string ref) {
    if (!character_id_reflist.contains(ref)) return ref;
    return character_id_reflist[ref];
}

std::string lowercase_str(std::string input) {
    std::transform(input.begin(), input.end(), input.begin(), [](unsigned char c) {
        return std::tolower(c);
    });
    return input;
}

    } // ASBR
} // nucc